export const ADD_TO_HISTORY = "ADD_TO_HISTORY";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const GET_CONTENT = "GET_CONTENT";
export const ADD_CONTENT = "ADD_CONTENT";
export const REMOVE_CONTENT = "REMOVE_CONTENT";
export const UPDATE_CONTENT = "UPDATE_CONTENT";
